/* automatically generated by rust-bindgen 0.69.5 */

pub const mtmd_input_chunk_type_MTMD_INPUT_CHUNK_TYPE_TEXT: mtmd_input_chunk_type = 0;
pub const mtmd_input_chunk_type_MTMD_INPUT_CHUNK_TYPE_IMAGE: mtmd_input_chunk_type = 1;
pub const mtmd_input_chunk_type_MTMD_INPUT_CHUNK_TYPE_AUDIO: mtmd_input_chunk_type = 2;
pub type mtmd_input_chunk_type = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mtmd_context {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mtmd_bitmap {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mtmd_image_tokens {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mtmd_input_chunk {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mtmd_input_chunks {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mtmd_batch {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mtmd_input_text {
    pub text: *const ::std::os::raw::c_char,
    pub text_len: usize,
    pub add_special: bool,
    pub parse_special: bool,
}
impl Default for mtmd_input_text {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type mtmd_progress_callback = ::std::option::Option<
    unsafe extern "C" fn(progress: f32, user_data: *mut ::std::os::raw::c_void) -> bool,
>;
#[repr(C)]
pub struct mtmd_context_params {
    pub use_gpu: bool,
    pub print_timings: bool,
    pub n_threads: ::std::os::raw::c_int,
    pub image_marker: *const ::std::os::raw::c_char,
    pub media_marker: *const ::std::os::raw::c_char,
    pub flash_attn_type: llama_flash_attn_type,
    pub warmup: bool,
    pub image_min_tokens: ::std::os::raw::c_int,
    pub image_max_tokens: ::std::os::raw::c_int,
    pub cb_eval: ggml_backend_sched_eval_callback,
    pub cb_eval_user_data: *mut ::std::os::raw::c_void,
    pub batch_max_tokens: i32,
    pub progress_callback: mtmd_progress_callback,
    pub progress_callback_user_data: *mut ::std::os::raw::c_void,
}
impl Default for mtmd_context_params {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl ::std::fmt::Debug for mtmd_context_params {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        write ! (f , "mtmd_context_params {{ use_gpu: {:?}, print_timings: {:?}, n_threads: {:?}, image_marker: {:?}, media_marker: {:?}, warmup: {:?}, image_min_tokens: {:?}, image_max_tokens: {:?}, cb_eval_user_data: {:?}, progress_callback: {:?}, progress_callback_user_data: {:?} }}" , self . use_gpu , self . print_timings , self . n_threads , self . image_marker , self . media_marker , self . warmup , self . image_min_tokens , self . image_max_tokens , self . cb_eval_user_data , self . progress_callback , self . progress_callback_user_data)
    }
}
extern "C" {
    pub fn mtmd_default_marker() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn mtmd_context_params_default() -> mtmd_context_params;
}
extern "C" {
    pub fn mtmd_init_from_file(
        mmproj_fname: *const ::std::os::raw::c_char,
        text_model: *const llama_model,
        ctx_params: mtmd_context_params,
    ) -> *mut mtmd_context;
}
extern "C" {
    pub fn mtmd_free(ctx: *mut mtmd_context);
}
extern "C" {
    pub fn mtmd_decode_use_non_causal(
        ctx: *const mtmd_context,
        chunk: *const mtmd_input_chunk,
    ) -> bool;
}
extern "C" {
    pub fn mtmd_decode_use_mrope(ctx: *const mtmd_context) -> bool;
}
extern "C" {
    pub fn mtmd_support_vision(ctx: *const mtmd_context) -> bool;
}
extern "C" {
    pub fn mtmd_support_audio(ctx: *const mtmd_context) -> bool;
}
extern "C" {
    pub fn mtmd_get_audio_sample_rate(ctx: *const mtmd_context) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn mtmd_get_marker(ctx: *const mtmd_context) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn mtmd_bitmap_init(
        nx: u32,
        ny: u32,
        data: *const ::std::os::raw::c_uchar,
    ) -> *mut mtmd_bitmap;
}
extern "C" {
    pub fn mtmd_bitmap_init_from_audio(n_samples: usize, data: *const f32) -> *mut mtmd_bitmap;
}
extern "C" {
    pub fn mtmd_bitmap_get_nx(bitmap: *const mtmd_bitmap) -> u32;
}
extern "C" {
    pub fn mtmd_bitmap_get_ny(bitmap: *const mtmd_bitmap) -> u32;
}
extern "C" {
    pub fn mtmd_bitmap_get_data(bitmap: *const mtmd_bitmap) -> *const ::std::os::raw::c_uchar;
}
extern "C" {
    pub fn mtmd_bitmap_get_n_bytes(bitmap: *const mtmd_bitmap) -> usize;
}
extern "C" {
    pub fn mtmd_bitmap_is_audio(bitmap: *const mtmd_bitmap) -> bool;
}
extern "C" {
    pub fn mtmd_bitmap_free(bitmap: *mut mtmd_bitmap);
}
extern "C" {
    pub fn mtmd_bitmap_get_id(bitmap: *const mtmd_bitmap) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn mtmd_bitmap_set_id(bitmap: *mut mtmd_bitmap, id: *const ::std::os::raw::c_char);
}
pub type mtmd_bitmap_lazy_callback = ::std::option::Option<
    unsafe extern "C" fn(
        chunk_idx: usize,
        user_data: *mut ::std::os::raw::c_void,
        out_bitmap: *mut *mut mtmd_bitmap,
        out_text: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int,
>;
extern "C" {
    pub fn mtmd_bitmap_init_lazy(
        ctx: *mut mtmd_context,
        id: *const ::std::os::raw::c_char,
        user_data: *mut ::std::os::raw::c_void,
        callback: mtmd_bitmap_lazy_callback,
    ) -> *mut mtmd_bitmap;
}
extern "C" {
    pub fn mtmd_input_chunks_init() -> *mut mtmd_input_chunks;
}
extern "C" {
    pub fn mtmd_input_chunks_size(chunks: *const mtmd_input_chunks) -> usize;
}
extern "C" {
    pub fn mtmd_input_chunks_get(
        chunks: *const mtmd_input_chunks,
        idx: usize,
    ) -> *const mtmd_input_chunk;
}
extern "C" {
    pub fn mtmd_input_chunks_free(chunks: *mut mtmd_input_chunks);
}
extern "C" {
    pub fn mtmd_input_chunk_get_type(chunk: *const mtmd_input_chunk) -> mtmd_input_chunk_type;
}
extern "C" {
    pub fn mtmd_input_chunk_get_tokens_text(
        chunk: *const mtmd_input_chunk,
        n_tokens_output: *mut usize,
    ) -> *const llama_token;
}
extern "C" {
    pub fn mtmd_input_chunk_get_tokens_image(
        chunk: *const mtmd_input_chunk,
    ) -> *const mtmd_image_tokens;
}
extern "C" {
    pub fn mtmd_input_chunk_get_n_tokens(chunk: *const mtmd_input_chunk) -> usize;
}
extern "C" {
    pub fn mtmd_input_chunk_get_id(chunk: *const mtmd_input_chunk)
        -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn mtmd_input_chunk_get_n_pos(chunk: *const mtmd_input_chunk) -> llama_pos;
}
extern "C" {
    pub fn mtmd_input_chunk_copy(chunk: *const mtmd_input_chunk) -> *mut mtmd_input_chunk;
}
extern "C" {
    pub fn mtmd_input_chunk_free(chunk: *mut mtmd_input_chunk);
}
extern "C" {
    pub fn mtmd_image_tokens_get_n_tokens(image_tokens: *const mtmd_image_tokens) -> usize;
}
extern "C" {
    pub fn mtmd_image_tokens_get_id(
        image_tokens: *const mtmd_image_tokens,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn mtmd_image_tokens_get_n_pos(image_tokens: *const mtmd_image_tokens) -> llama_pos;
}
extern "C" {
    pub fn mtmd_image_tokens_get_nx(image_tokens: *const mtmd_image_tokens) -> usize;
}
extern "C" {
    pub fn mtmd_image_tokens_get_ny(image_tokens: *const mtmd_image_tokens) -> usize;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct mtmd_decoder_pos {
    pub t: u32,
    pub x: u32,
    pub y: u32,
    pub z: u32,
}
extern "C" {
    pub fn mtmd_image_tokens_get_decoder_pos(
        image_tokens: *const mtmd_image_tokens,
        pos_0: llama_pos,
        i: usize,
    ) -> mtmd_decoder_pos;
}
extern "C" {
    pub fn mtmd_tokenize(
        ctx: *mut mtmd_context,
        output: *mut mtmd_input_chunks,
        text: *const mtmd_input_text,
        bitmaps: *mut *const mtmd_bitmap,
        n_bitmaps: usize,
    ) -> i32;
}
extern "C" {
    pub fn mtmd_encode(ctx: *mut mtmd_context, image_tokens: *const mtmd_image_tokens) -> i32;
}
extern "C" {
    pub fn mtmd_encode_chunk(ctx: *mut mtmd_context, chunk: *const mtmd_input_chunk) -> i32;
}
extern "C" {
    pub fn mtmd_get_output_embd(ctx: *mut mtmd_context) -> *mut f32;
}
extern "C" {
    pub fn mtmd_batch_init(ctx: *mut mtmd_context) -> *mut mtmd_batch;
}
extern "C" {
    pub fn mtmd_batch_free(batch: *mut mtmd_batch);
}
extern "C" {
    pub fn mtmd_batch_add_chunk(batch: *mut mtmd_batch, chunk: *const mtmd_input_chunk) -> i32;
}
extern "C" {
    pub fn mtmd_batch_encode(batch: *mut mtmd_batch) -> i32;
}
extern "C" {
    pub fn mtmd_batch_get_output_embd(
        batch: *mut mtmd_batch,
        chunk: *const mtmd_input_chunk,
    ) -> *mut f32;
}
extern "C" {
    pub fn mtmd_log_set(log_callback: ggml_log_callback, user_data: *mut ::std::os::raw::c_void);
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct mtmd_caps {
    pub inp_vision: bool,
    pub inp_audio: bool,
}
extern "C" {
    pub fn mtmd_get_cap_from_file(mmproj_fname: *const ::std::os::raw::c_char) -> mtmd_caps;
}
extern "C" {
    pub fn mtmd_test_create_input_chunks() -> *mut mtmd_input_chunks;
}
