/* Auto-generated by cbindgen. Do not edit. */

#ifndef FORGE_FFI_H
#define FORGE_FFI_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Default FFT size for LFM2.5-Audio
#define DEFAULT_N_FFT 1280

// Default hop length for LFM2.5-Audio
#define DEFAULT_HOP_LENGTH 320

// Default sample rate for LFM2.5-Audio
#define DEFAULT_SAMPLE_RATE 24000

// Error codes returned by FFI functions
typedef enum ForgeResult {
  // Success
  ForgeResult_Ok = 0,
  // Null pointer passed
  ForgeResult_NullPointer = 1,
  // Model load failed
  ForgeResult_ModelLoadFailed = 2,
  // Context creation failed
  ForgeResult_ContextCreationFailed = 3,
  // Multimodal load failed
  ForgeResult_MultimodalLoadFailed = 4,
  // Tokenization failed
  ForgeResult_TokenizationFailed = 5,
  // Decode failed
  ForgeResult_DecodeFailed = 6,
  // Invalid parameter
  ForgeResult_InvalidParameter = 7,
  // Memory budget exceeded
  ForgeResult_MemoryExceeded = 8,
  // Generation was cancelled by the caller
  ForgeResult_Cancelled = 9,
  // Unknown error
  ForgeResult_Unknown = 99,
} ForgeResult;

// Configuration parameters passed from Swift
typedef struct ForgeParams {
  // Context size
  uint32_t n_ctx;
  // Batch size
  uint32_t n_batch;
  // Number of threads
  int32_t n_threads;
  // Maximum tokens to generate
  uint32_t max_tokens;
  // Temperature (0.0 = greedy)
  float temperature;
  // Top-K sampling
  int32_t top_k;
  // Top-P sampling
  float top_p;
  // Memory budget in MB (0 = unlimited)
  uint32_t memory_budget_mb;
  // Enable flash attention
  bool flash_attn;
  // Number of GPU layers (-1 = all)
  int32_t n_gpu_layers;
} ForgeParams;

// Opaque type for the Forge engine (C representation)
// This is never constructed directly - only through pointers
typedef struct ForgeEngineOpaque {
  uint8_t _private[0];
} ForgeEngineOpaque;

// Opaque handle to the Forge engine
typedef struct ForgeEngineOpaque *ForgeHandle;

// Callback type for streaming token output
typedef void (*TokenCallback)(const char *token, void *user_data);

// Audio output configuration
typedef struct ForgeAudioConfig {
  // FFT size (default: 1280 for LFM2.5-Audio)
  uint32_t n_fft;
  // Hop length in samples (default: 320)
  uint32_t hop_length;
  // Sample rate in Hz (default: 24000)
  uint32_t sample_rate;
} ForgeAudioConfig;

// Opaque type for the audio decoder (vocoder)
typedef struct ForgeAudioDecoderOpaque {
  uint8_t _private[0];
} ForgeAudioDecoderOpaque;

// Opaque handle to the audio decoder
typedef struct ForgeAudioDecoderOpaque *ForgeAudioDecoderHandle;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Initialize the Forge backend. Must be called once before any other functions.
void forge_init(void);

// Cleanup the Forge backend. Call when completely done with inference.
void forge_cleanup(void);

// Get default parameters
struct ForgeParams forge_params_default(void);

// Get the default media marker string for image prompts
//
// Returns a pointer to a static string like "<image>" or "<__media__>".
// The returned string is valid until the next call to this function.
//
// # Example
//
// ```c
// const char* marker = forge_get_media_marker();
// // Use marker in prompt: "<|im_start|>user\n{marker}\nWhat is this?\n<|im_end|>"
// ```
const char *forge_get_media_marker(void);

// Create a new Forge engine for text-only inference
//
// # Arguments
//
// * `model_path` - Path to the GGUF model file (null-terminated)
// * `params` - Configuration parameters
//
// # Returns
//
// Handle to the engine, or NULL on failure
ForgeHandle forge_engine_create(const char *model_path, const struct ForgeParams *params);

// Create a new Forge engine with vision capabilities
//
// # Arguments
//
// * `model_path` - Path to the GGUF model file
// * `clip_path` - Path to the CLIP model file (mmproj-*.gguf)
// * `params` - Configuration parameters
//
// # Returns
//
// Handle to the engine, or NULL on failure
ForgeHandle forge_engine_create_vision(const char *model_path,
                                       const char *clip_path,
                                       const struct ForgeParams *params);

// Destroy a Forge engine and free all resources
//
// # Safety
//
// The handle must have been created by forge_engine_create or forge_engine_create_vision.
// After calling this, the handle is invalid and must not be used.
void forge_engine_destroy(ForgeHandle engine);

// Request cancellation of the active generation without waiting for the engine lock.
// Safe to call from a different thread while a generation callback is running.
enum ForgeResult forge_cancel(ForgeHandle engine);

// Generate text from a prompt (single-turn, clears context)
//
// # Arguments
//
// * `engine` - Engine handle
// * `prompt` - Input prompt (null-terminated)
// * `callback` - Called for each generated token
// * `user_data` - Passed to callback
//
// # Returns
//
// ForgeResult::Ok on success, error code on failure
enum ForgeResult forge_generate(ForgeHandle engine,
                                const char *prompt,
                                TokenCallback callback,
                                void *user_data);

// Generate a response for a conversation turn (multi-turn aware)
//
// This properly handles:
// - BOS token: Only added when add_bos is true (should be first turn only)
// - EOG feedback: Previous EOG token is fed back to model
// - Context accumulation: Maintains conversation history
//
// # Arguments
//
// * `engine` - Engine handle
// * `prompt` - Formatted prompt for this turn (null-terminated)
// * `add_bos` - Whether to add BOS token (true for first turn only)
// * `callback` - Called for each generated token
// * `user_data` - Passed to callback
//
// # Example Usage
//
// ```c
// // First turn - add BOS
// forge_generate_turn(engine, "<|im_start|>user\nHello\n<|im_end|><|im_start|>assistant\n",
//                     true, callback, user_data);
//
// // Second turn - no BOS, context preserved
// forge_generate_turn(engine, "<|im_start|>user\nHow are you?\n<|im_end|><|im_start|>assistant\n",
//                     false, callback, user_data);
// ```
enum ForgeResult forge_generate_turn(ForgeHandle engine,
                                     const char *prompt,
                                     bool add_bos,
                                     TokenCallback callback,
                                     void *user_data);

// Check if this is the first turn (n_past == 0)
//
// Use this to determine whether to add BOS token in chat template
bool forge_is_first_turn(ForgeHandle engine);

// Get the current context position (tokens processed so far)
int32_t forge_n_past(ForgeHandle engine);

// Set the number of tokens to preserve when context sliding occurs
//
// When the context fills up, the engine will automatically shift the context
// to make room for new tokens. This setting controls how many tokens at the
// beginning are preserved (typically the system prompt).
//
// # Arguments
//
// * `engine` - Engine handle
// * `n_keep` - Number of tokens to keep (0 = don't preserve any)
void forge_set_n_keep(ForgeHandle engine, int32_t n_keep);

// Get the current n_keep setting
int32_t forge_get_n_keep(ForgeHandle engine);

// Check if context sliding is supported
//
// Returns true if the engine's memory supports shifting (context sliding).
// Most models support this, but some specialized models may not.
bool forge_can_shift_context(ForgeHandle engine);

// Generate text from an image (JPEG/PNG) and prompt
//
// # Arguments
//
// * `engine` - Engine handle (must have vision enabled)
// * `image_data` - Encoded image data (JPEG, PNG, etc.)
// * `image_len` - Length of image data
// * `prompt` - Text prompt (null-terminated, should contain image marker)
// * `callback` - Called for each generated token
// * `user_data` - Passed to callback
enum ForgeResult forge_generate_vision(ForgeHandle engine,
                                       const uint8_t *image_data,
                                       uintptr_t image_len,
                                       const char *prompt,
                                       TokenCallback callback,
                                       void *user_data);

// Generate text from an image and prompt (vision models)
//
// # Arguments
//
// * `engine` - Engine handle (must have vision enabled)
// * `width` - Image width in pixels
// * `height` - Image height in pixels
// * `rgba_data` - Raw RGBA pixel data (4 bytes per pixel)
// * `rgba_len` - Length of RGBA data (should be width * height * 4)
// * `prompt` - Text prompt (null-terminated, should contain image marker)
// * `callback` - Called for each generated token
// * `user_data` - Passed to callback
enum ForgeResult forge_generate_vision_rgba(ForgeHandle engine,
                                            uint32_t width,
                                            uint32_t height,
                                            const uint8_t *rgba_data,
                                            uintptr_t rgba_len,
                                            const char *prompt,
                                            TokenCallback callback,
                                            void *user_data);

// Reset the conversation context (clear KV cache)
enum ForgeResult forge_reset(ForgeHandle engine);

// Get current memory usage in MB
double forge_memory_current_mb(ForgeHandle engine);

// Get peak memory usage in MB
double forge_memory_peak_mb(ForgeHandle engine);

// Get default audio configuration for LFM2.5-Audio
struct ForgeAudioConfig forge_audio_config_default(void);

// Create a new audio decoder (vocoder) with default parameters
//
// # Returns
//
// Handle to the decoder, or NULL on failure
ForgeAudioDecoderHandle forge_audio_decoder_create(void);

// Create a new audio decoder with custom parameters
//
// # Arguments
//
// * `config` - Audio configuration
//
// # Returns
//
// Handle to the decoder, or NULL on failure
ForgeAudioDecoderHandle forge_audio_decoder_create_with_config(const struct ForgeAudioConfig *config);

// Destroy an audio decoder and free resources
//
// # Safety
//
// The handle must have been created by forge_audio_decoder_create.
// After calling this, the handle is invalid.
void forge_audio_decoder_destroy(ForgeAudioDecoderHandle decoder);

// Process embeddings and generate audio samples
//
// This is the main vocoder function. It takes magnitude/phase embeddings
// from the LLM and converts them to PCM audio samples.
//
// # Arguments
//
// * `decoder` - Audio decoder handle
// * `embeddings` - Model output embeddings (magnitude + phase, interleaved)
// * `embedding_len` - Number of embedding values (should be n_fft_bins * 2)
// * `output` - Buffer to write PCM samples (f32, -1.0 to 1.0)
// * `output_capacity` - Size of output buffer in samples
// * `samples_written` - Output: number of samples actually written
//
// # Returns
//
// ForgeResult::Ok on success, error code on failure
enum ForgeResult forge_audio_decoder_process(ForgeAudioDecoderHandle decoder,
                                             const float *embeddings,
                                             uintptr_t embedding_len,
                                             float *output,
                                             uintptr_t output_capacity,
                                             uintptr_t *samples_written);

// Flush remaining audio samples at end of stream
//
// Call this after processing all frames to get the final samples
// that are still in the overlap buffer.
//
// # Arguments
//
// * `decoder` - Audio decoder handle
// * `output` - Buffer to write PCM samples
// * `output_capacity` - Size of output buffer in samples
// * `samples_written` - Output: number of samples actually written
//
// # Returns
//
// ForgeResult::Ok on success
enum ForgeResult forge_audio_decoder_flush(ForgeAudioDecoderHandle decoder,
                                           float *output,
                                           uintptr_t output_capacity,
                                           uintptr_t *samples_written);

// Reset the audio decoder state
//
// Call this when starting a new audio stream.
enum ForgeResult forge_audio_decoder_reset(ForgeAudioDecoderHandle decoder);

// Get the expected embedding size per frame
//
// This is the number of f32 values expected per call to process.
// For LFM2.5-Audio with n_fft=1280, this is 1282 (641 bins * 2).
uintptr_t forge_audio_decoder_embedding_size(ForgeAudioDecoderHandle decoder);

// Get the sample rate of the audio decoder
uint32_t forge_audio_decoder_sample_rate(ForgeAudioDecoderHandle _decoder);

// Check if the engine supports audio input
//
// Returns true if the engine was created with an audio-capable model.
bool forge_engine_supports_audio(ForgeHandle engine);

// Get the expected audio sample rate for input
//
// Returns the sample rate in Hz (e.g., 16000 for most speech models).
// Returns 0 if audio is not supported.
uint32_t forge_engine_audio_sample_rate(ForgeHandle engine);

// Generate a response from audio input
//
// This processes raw PCM audio samples and generates a text or audio response.
//
// # Arguments
//
// * `engine` - Engine handle (must have audio enabled)
// * `samples` - PCM audio samples (f32, normalized -1.0 to 1.0)
// * `n_samples` - Number of audio samples
// * `prompt` - Text prompt (should contain media marker, null-terminated)
// * `callback` - Called for each generated token
// * `user_data` - Passed to callback
//
// # Returns
//
// ForgeResult::Ok on success, error code on failure
enum ForgeResult forge_generate_audio(ForgeHandle engine,
                                      const float *samples,
                                      uintptr_t n_samples,
                                      const char *prompt,
                                      TokenCallback callback,
                                      void *user_data);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* FORGE_FFI_H */
